config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :events do
    resources :tickets, only: [:index, :create]
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :tickets, dependent: :destroy

  validates :name, :date_time, :total_tickets, presence: true

  scope :ordered_by_user, ->(user_id) {
    order(Arel.sql("CASE WHEN events.user_id = ? THEN 0 ELSE 1 END, created_at", user_id))
  }

  scope :booked_tickets, ->{
    joins(:tickets)
      .group(:event_id)
      .select("events.*, SUM(tickets.quantity) AS quantity")
  }

  def available_tickets
    total_tickets - tickets.sum(:quantity)
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  scope :my_booked_tickets, -> {
    joins(:event)
      .group('events.id')
      .select('*, SUM(tickets.quantity) AS total_quantity')
  }

  # Add lock_version for optimistic locking
  self.ignored_columns = [:lock_version]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tickets, dependent: :destroy
  has_many :events, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def booked_events
    tickets.map(&:event).uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event , except: [:create, :index, :new]

  def index
    if user_signed_in?
      @my_booked_events = current_user.events.booked_tickets
      @my_booked_tickets = current_user.tickets.my_booked_tickets
      @events = Event.ordered_by_user(current_user.id).booked_tickets
    else
      @events = Event.all
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    event = current_user.events.build(event_params)
    if event.save
      redirect_to event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully destroyed'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date_time, :total_tickets)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :authenticate_user!

    def create
      @event = Event.find(params[:event_id])
      # if current_user.events.include? @event
      #   redirect_to @event, alert: "You can't book your Event's ticket"
      #   return
      # end
      quantity = params[:quantity].to_i
      if quantity <= 0
        redirect_to root_path, alert: 'Invalid quantity.'
        return
      end

      begin
        Ticket.transaction do
          tickets_available = @event.available_tickets
          if quantity > tickets_available
            raise ArgumentError, 'Not enough tickets available.'
          end

          current_user.tickets.create!(event: @event, quantity: quantity)
        end

        redirect_to root_path, notice: 'Tickets booked successfully.'
      rescue ArgumentError => e
        redirect_to @event, alert: e.message
      rescue ActiveRecord::StaleObjectError
        redirect_to @event, alert: 'Another user has booked tickets for this event. Please try again.'
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def booked_tickets_count(user, event)
      event.tickets.booked_tickets(user, event)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_booking_list.html.erb
<table class="table">
  <thead>
      <tr>
          <th>Name</th>
          <th>Description</th>
          <th>location</th>
          <th>Booked Ticket</th>
          <th>Date time</th>
      </tr>
  </thead>
  <tbody>
      <% my_booked_events.each do |event| %>
          <tr>
              <td><%=event.name %></td>
              <td><%=event.description %></td>
              <td><%=event.location %></td>
              <td><%= event.total_quantity %></td>
              <td><%=event.date_time %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/events/_event.html.erb
<tr>
    <td><%=event.name %></td>
    <td><%=event.description %></td>
    <td><%=event.location %></td>
    <td><%=event.total_tickets %></td>
    <td><%=event.available_tickets %></td>
    <td><%=event.date_time %></td>
    <td><%= link_to :see_event, event_path(event) %></td>
    <% if event.user.eql? current_user%>
        <td><%= event.quantity %></td>
        <td><%= "MY EVENT"  %></td>
    <% else %>
        <td> - </td>
        <td> - </td>
    <%end %>
</tr>

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, class: 'form') do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name,class: 'form-label' %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :location,class: 'form-label' %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :date_time,class: 'form-label' %>
    <%= form.datetime_local_field :date_time, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :total_tickets,class: 'form-label' %>
    <%= form.number_field :total_tickets, class: "form-control" %>
  </div>

  <div class="actions my-2">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render 'form' %>
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h2 class="d-inline">All Events</h2>
    <%= link_to "Create Event", new_event_path, class: "btn btn-primary ms-auto d-inline" %>
</div>
<% unless @events.blank? %>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>location</th>
                <th>Total Ticket</th>
                <th>Available Ticket</th>
                <th>Date time</th>
                <th>Action</th>
                <th>Booked Tickets</th>
            </tr>
        </thead>
        <tbody>
            <%= render @events %>
        </tbody>
    </table>
<% else %>
    <h5 class="text-center">No Events Available Yet</h5>
<% end %>

<% if user_signed_in? %>
    <h3>My Booked Tickets</h3>
    <%= render "booking_list", my_booked_events: @my_booked_tickets %>
<% end %>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto my-5">
        <h1>New Event</h1>
        <%= render 'form' %>
        <%= link_to 'Back', events_path, class: "btn btn-sm btn-secondary" %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to "Destroy", event_path(@event), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

<ul class="list-group list-group-flush">
  <li class="list-group-item"><h1><%= @event.name.capitalize %></h1></li>
  <li class="list-group-item"><strong>Location:</strong><%= @event.location %></li>
  <li class="list-group-item"><strong>Date:</strong><%= @event.date_time %></li>
  <li class="list-group-item"><strong>Total Tickets:</strong> <%= @event.total_tickets %></li>
  <li class="list-group-item"><strong>Available Tickets:</strong> <%= @event.available_tickets %></li>
</ul>

<div class="my-3">
  <%= form_with url: event_tickets_path(@event), method: :post do |f|%>
      <h3>Book Ticket</h3>
      <%= f.label :ticket_quantity, class: "form-label" %>
      <%= f.number_field :quantity, class: "form-control mb-2" %>
      <%= f.submit "Book Ticket", class: "btn btn-dark"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/errors" %>
  <div class="container py-3">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:notice].nil? && flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% elsif flash[:alert].nil? && flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="#">Ticketing Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-2">
          <li class="nav-item">
            <%= link_to :Home, root_path, class: "nav-link" %>
          </li>
        </ul>
        <form class="d-flex ms-auto">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, data: {
              turbo_method: :delete
            }, class: "btn btn-dark" %>
          <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-dark"  %>
          <% end %>
        </form>
      </div>
  </div>
</nav>

app/views/tickets/index.html.erb
<% @user_events.each do |ticket| %>
  <div>
    <h2><%= link_to ticket.event.name, ticket.event %></h2>
    <p><strong>Quantity:</strong> <%= ticket.quantity %></p>
  </div>
<% end %>